### ISSUE TITLE
long wait when numCPU > 1 in breakpointr()

### ISSUE THREAD

**Issue by benedict909** [daewoooo/breakpointR#14]
Hello,

I've just started a PhD with Ashley in Berlin, thanks for this great tool!

When I try and run `breakpointr()` with numCPU set to any value > 1 nothing happens for a very long time, meaning it is actually quicker for me to run the function with `numCPU = 1`. 

Here is the point at which it stalls:

`Using 2 CPUs`
`Finding breakpoints ...`

Do you have any idea why this might be? It would be great if I could parallelise this as I am running breakpointR as part of a pipeline on lots of cells at once!
It happens for me both on our HPC cluster and on my local machine which are running different R versions, so I don't think its an issue with my installations.

Thank you, 
Benedict

**Comment by daewoooo** [comment]
Hi Benedict,

Sorry as this breakpointR messaging might be confusing. When it reports "Using 2 CPUs Finding breakpoints ..." breakpointR actually is already running on 2CPUs and when done it will report total time of the analysis. In multi-core run this is the only message you get. But you can see in your outputfolder that analyzed data are piling up.

David

**Comment by benedict909** [comment]
Ah I see thank you, sorry I was expecting the same verbosity as you get when using 1 CPU (although now I think about it I see why this wouldn't really work when processing multiple samples at once!).
