### ISSUE TITLE
Error when no breakpoints detected

### ISSUE THREAD

**Issue by vincent-hanlon** [daewoooo/breakpointR#15]
BreakpointR returns an error (or an empty Breakpoints object) when a it is run on a Strand-seq library that doesn't have strand-switches. I think this is probably the intended behaviour of the package. I sometimes encounter this when running (i) a BAM file that contains only a few chromosomes, (ii) a BAM file from which error prone always-Watson-Crick reads have been removed, and/or (iii) with very large binsizes. I think some errors I have when running with very low-coverage BAM files may also be related to this. 

Would it be possible to alter the behaviour of BreakpointR so it does not return an error but instead returns a Breakpoints object that contains $fragments, $deltas, and $counts, but no $breaks and no $confints? 

I understand that other users might have other priorities (and I have no idea if this is an easy fix or a difficult one), but I would find this helpful. It would be especially useful for making composite files, because the 'states' attribute of the $counts object would be able to say which chromosomes are wc, ww, or cc even when no breakpoints are found in a library.

**Comment by vincent-hanlon** [comment]
After further testing, I think this issue was just a sneaky manifestation of Issue #16, "maskRegions removes all reads". Case closed?

**Comment by daewoooo** [comment]
Seems like bug in maskRegions is causing lot of troubles. I will resolve this next week. Thanks for all the troubleshooting work!
