### ISSUE TITLE
maskRegions removes all reads

### ISSUE THREAD

**Issue by vincent-hanlon** [daewoooo/breakpointR#16]
Summary: when the blacklist isn't doing anything it throws out all reads instead of throwing out no reads.

`runBreakpointr()` can apply a blacklist to reads using `maskRegions`. The blacklist is supposed to remove the reads from the `fragments` GRanges object. It uses this code to do so:

```
mask <- IRanges::findOverlaps(maskRegions, fragments)
fragments <- fragments[-S4Vectors::subjectHits(mask)]
```

The problem occurs when `maskRegions` and `fragments` do not overlap, that is, when the blacklist isn't supposed to remove any reads at all. Unfortunately, in that case there are no overlaps, so `mask` has length zero. This means `subjectHits(mask)` is `integer(0)` and it's equal to `-subjectHits(mask)`. When the `fragments`  object is subset to `integer(0)`, an empty GRanges object is returned. 

I think probably `fragments <- fragments[-S4Vectors::subjectHits(mask)]` should be wrapped in an if statement to check whether `length(mask)>0`.

**Comment by daewoooo** [comment]
Resolved in the current version in devel branch. Fix will be added at the next Bioconductor release.
