### ISSUE TITLE
filtering for several chromosomes broken

### ISSUE THREAD

**Issue by ptrebert** [daewoooo/breakpointR#4]
R 3.5.1
[1] breakpointR_0.99.11    breakpointRdata_0.99.2

Calling `breakpointr` with a list such as `chroms = c('chr1', 'chr2', 'chr3')` of chromosomes for the option `chromosomes=` leads to immediate failure when the config file is being dumped. Wild guess is that using `cat` to write the config file cannot handle this (if no list should be supplied for this option, please update the manual/docs)

**Comment by daewoooo** [comment]
Please check if this problem still remains.

**Comment by ptrebert** [comment]
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

[1] breakpointR_1.1.0      breakpointRdata_0.99.2

Seems to work fine now; list of chromosomes appears in the dumped config and no breakpoints from filtered chromosomes appear in the output - looks all great, thanks!

+Peter
