### ISSUE TITLE
improve handling of small chromosomes

### ISSUE THREAD

**Issue by ptrebert** [daewoooo/breakpointR#5]
R 3.5.1
[1] breakpointR_0.99.11    breakpointRdata_0.99.2

breakpointR fails for genome tiling operations on small chromosomes, i.e., when the chromosome size is shorter than the selected tiling window (happens, e.g., for chrM). This could be handled more gracefully by simply skipping over small chromosomes and printing a warning (or similar)

I think this is an example line in `plotting.R`
```R
binned.data <- unlist(GenomicRanges::tileGenome(seqlengths(reads), tilewidth = 200000))
```

**Comment by daewoooo** [comment]
FIXED
