### ISSUE TITLE
maskRegions broken

### ISSUE THREAD

**Issue by ptrebert** [daewoooo/breakpointR#6]
R 3.5.1
[1] breakpointR_0.99.11    breakpointRdata_0.99.2

It seems impossible to use regions for masking if no chromosomes are specified:

```R
In breakpointr(inputfolder = input, outputfolder = output, reuse.existing.files = TRUE,  :
  Skipping maskRegions. Chromosomes names conflict: chr1 not equal 
```
This seems to be caused by the fact that not specifying chromosomes/a list of chromosomes leaves that option empty, presumably leading to a `FALSE` for this `if ...`

```R
if (any(mask.df$V1 %in% chromosomes))
```

**Comment by daewoooo** [comment]
FIXED
