### ISSUE TITLE
unable to find an inherited method for function ‘disjoin’ for signature ‘"NULL"’.

### ISSUE THREAD

**Issue by EXGDT** [daewoooo/breakpointR#9]
R version: 3.6.1
After writing the result, it's broken.
`Writing to file /public/home/yxguo/test/breakpointR_result/browserfiles/XXX_bwa_filter.sorted.sorted.bam_reads.bed.gz ... 1696.08s

Writing to file /public/home/yxguo/test/breakpointR_result/browserfiles/XXX_filter.sorted.sorted.bam_deltaWs.bed.gz ... 0.37s

Error in (function (classes, fdef, mtable)  : 

  unable to find an inherited method for function ‘disjoin’ for signature ‘"NULL"’

Calls: breakpointr -> <Anonymous> -> <Anonymous>

Execution halted`

**Comment by daewoooo** [comment]
Hi,

Would be great to know what data are you analyzing and what set of parameters you used to run breakpointR.
I will dig into this when I have more info and be able to reproduce the error.

David

**Comment by EXGDT** [comment]
@daewoooo Hi,

Sorry, I forgot giving the information of my data. Because I have no Strand-Seq data now, some normal Illumina WGS data were used to have a try, all the parameters set to default.
Maybe the  WGS data cannot be used for breakpointR? But I think the WGS data cannot result in this "disjoin function error".  Anyway, sorry to open the issue for the incorrect operation.

**Comment by daewoooo** [comment]
Hi no problem at all. Indeed standard Illumina data might not work as expected.
Anyway I will have a look into the "disjoin function error" to make sure it's not unexpected bug.
Thanks for pointing it out to me.

**Comment by daewoooo** [comment]
Resolved by informative STOP directive if not breakpoints are detected. User is referred to check if the parameters are correct and if the correct Strand-seq data are being processed.
